require 'fileutils'

default_platform(:ios)

platform :ios do
  desc "Run tests for the SPM"
  lane :tests do
    spm(
      command: 'generate-xcodeproj',
      enable_code_coverage: true
    )
    run_tests(
      project: 'DisguisedSwiftly.xcodeproj',
      scheme: 'DisguisedSwiftly-Package',
      device: 'iPhone 12',
      clean: true
    )
  end
end
  
after_all do
  FileUtils.remove_dir './../DisguisedSwiftly.xcodeproj', true
end

desc "Does a static analysis of the project. Configure the options in .swiftlint.yml"
lane :lint do
        swiftlint(
          mode: :lint,
          output_file: "swiftlint.result.json", 
          config_file: ".swiftlint.yml"
        )
end